### ISSUE TITLE
Function name shortening

### ISSUE THREAD

**Issue by jared-hughes** [jared-hughes/DesThree#15]
Expressions get too long, too quickly. Changing functions like `ColorRGB` to `RGB`, `IcosahedronGeometry` → `Icosahedron`, `MeshBasicMaterial`→`BasicMaterial`, etc. would improve this situation. 

This should happen soon to allow for better backwards compatibility.

**Comment by jared-hughes** [comment]
Proposed Migration Table:

Before | After
---: | :---
ColorRGB | RGB
MeshBasicMaterial | BasicMaterial
MeshLambertMaterial | LambertMaterial
MeshToonMaterial | ToonMaterial
MeshNormalMaterial | NormalMaterial
MeshDepthMaterial | DepthMaterial
MeshPhongMaterial | PhongMaterial
IcosahedronGeometry | Icosahedron
DodecahedronGeometry | Dodecahedron
OctahedronGeometry | Octahedron
TetrahedronGeometry | Tetrahedron
SphereGeometry | Sphere
TorusGeometry | Torus
TorusKnotGeometry | TorusKnot
CylinderGeometry | Cylinder
FrustumGeometry | Frustum
ConeGeometry | Cone
BoxGeometry | Box
Mesh | Mesh
PointLight | PointLight
AmbientLight | AmbientLight
PerspectiveCamera | PerspectiveCamera
Position | Position
Show | Show

Some comments:

 - There is a `LineBasicMaterial` in three.js. If that gets added, just include the "Line" prefix in the `Line***Material` functions to make their names distinct from the abbreviated `Mesh***Material`s. 
 - Removing `Geometry` from the names is pretty much necessary for brevity, but makes it slightly less clear that the function produces a geometry. I don't think that is a big concern though

**Comment by SlimRunner** [comment]
Seems like a good idea, especially considering the that the custom operator names are still a bit unstable while typing. Less typing goes a long way.
