### ISSUE TITLE
Load error when expression is in collapsed folder

### ISSUE THREAD

**Issue by SlimRunner** [jared-hughes/DesThree#21]
The error is not catastrophic. It is an uncaught exception that occurs when a graph is loaded with a DesThree expression inside a collapsed folder. Upon expanding the collapsed folder the script continues execution as normal. Test graph [https://www.desmos.com/calculator/16szwajkgv](https://www.desmos.com/calculator/16szwajkgv)

Error message is `Uncaught TypeError: this.getExprElement(...) is null` and occurs within `setExprError`.

**Comment by jared-hughes** [comment]
Looks like this is fixed, probably from ef1ae486e8b1e881c878180ff5d9b4734d816f85, so I am closing it.
